// apps/website-nextjs/src/components/auth/SignInForm/SignInForm.tsx
"use client";

import React, { useTransition } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useFormState } from "react-dom";
import { useForm } from "react-hook-form";

import type { FormFieldSignUpSchema } from "@template/sdk";
import { schema } from "@template/sdk";
import { cn } from "@template/ui";
import { Button } from "@template/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@template/ui/form";
import { Input } from "@template/ui/input";
import { isBoolean, isUndefined } from "@template/utils/assertion";

import type { State } from "~/components/auth/SignInForm/signin.action";
import { submitAction } from "~/components/auth/SignInForm/signin.action";
import { Icons } from "~/components/icons";
import { InputPassword } from "~/components/shared/InputPassword";

export default function SignInForm() {
  const [isPending, startTransition] = useTransition();

  const [state, formAction] = useFormState<State, FormFieldSignUpSchema>(
    submitAction,
    undefined,
  );

  const form = useForm<FormFieldSignUpSchema>({
    progressive: true,
    resolver: zodResolver(schema.signIn),
    defaultValues: {
      email: "",
      password: "",
    },
    errors: isUndefined(state) || isBoolean(state) ? undefined : state,
    reValidateMode: "onBlur",
  });

  return (
    <div className="grid gap-6">
      <Form {...form}>
        <form
          id="signin-form"
          onSubmit={form.handleSubmit((input) => {
            startTransition(() => formAction(input));
          })}
        >
          <div className="grid gap-5">
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>이메일</FormLabel>
                  <FormControl>
                    <Input
                      data-testid="email"
                      placeholder="example@example.com"
                      autoCapitalize="none"
                      autoComplete="email"
                      autoCorrect="off"
                      dir="ltr"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>비밀번호</FormLabel>
                  <FormControl>
                    <InputPassword
                      placeholder="비밀번호"
                      autoComplete="current-password"
                      dir="ltr"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <Button
              type="submit"
              disabled={isPending}
              aria-disabled={isPending}
            >
              {isPending ? (
                <Icons.spinner className="mr-2 size-4 animate-spin" />
              ) : null}
              <span>로그인</span>
            </Button>
          </div>
        </form>
      </Form>
      <div className="relative">
        <div className="absolute inset-0 flex items-center">
          <span className="w-full border-t" />
        </div>
        <div className="relative flex justify-center text-xs uppercase">
          <span className={cn("bg-background px-2 text-muted-foreground")}>
            또는
          </span>
        </div>
      </div>
    </div>
  );
}

// apps/website-sveltekit/src/lib/components/auth/SignInForm/SignInForm.svelte
<script lang="ts">
  import { Icons } from "$lib/components/icon";
  import * as Form from "$lib/components/ui/form";
  import { Input } from "$lib/components/ui/input";
  import { InputPassword } from "$lib/components/ui/input-password";
  import { superForm } from "sveltekit-superforms";
  import { zodClient } from "sveltekit-superforms/adapters";

  import { schema } from "@template/sdk";

  import type { PageData } from "../../../../routes/(auth)/signin/$types";

  export let data: PageData;

  let loading = false;

  const form = superForm(data.form, {
    validators: zodClient(schema.signIn),
    dataType: "json",
    onSubmit: () => {
      loading = true;
    },
    onError: () => {
      loading = false;
    },
    onUpdate: () => {
      loading = false;
    },
  });

  const { form: formData, enhance, delayed } = form;
</script>

<div class="grid gap-6">
  <form id="signin-form" data-testid="signin-form" method="POST" use:enhance>
    <div class="grid gap-5">
      <Form.Field {form} name="email">
        <Form.Control let:attrs>
          <Form.Label>이메일</Form.Label>
          <Input
            data-testid="email"
            placeholder="example@example.com"
            autocapitalize="none"
            autocomplete="email"
            autocorrect="off"
            {...attrs}
            bind:value={$formData.email}
          />
        </Form.Control>
        <Form.FieldErrors />
      </Form.Field>
      <Form.Field {form} name="password">
        <Form.Control let:attrs>
          <Form.Label>비밀번호</Form.Label>
          <InputPassword
            data-testid="password"
            placeholder="비밀번호"
            autocomplete="current-password"
            {...attrs}
            bind:value={$formData.password}
          />
        </Form.Control>
        <Form.FieldErrors />
      </Form.Field>
      <Form.Button type="submit" data-testid="signin-button">
        {#if loading}
          <Icons.spinner class="mr-2 size-4 animate-spin" />
        {/if}
        <span>로그인</span>
      </Form.Button>
    </div>
  </form>
  <div class="relative">
    <div class="absolute inset-0 flex items-center">
      <span class="w-full border-t" />
    </div>
    <div class="relative flex justify-center text-xs uppercase">
      <span class="bg-background px-2 text-muted-foreground"> 또는 </span>
    </div>
  </div>
</div>
