// apps/website-remix/app/components/shared/InputPassword/InputPassword.tsx
import type { LucideProps } from "lucide-react";
import * as React from "react";

import { Button } from "@template/ui/button";
import { Input } from "@template/ui/input";

import { Icons } from "~/components/icons";

export type InputPasswordProps = Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  "type"
> & { iconEyeProps?: LucideProps; iconEyeOffProps?: LucideProps };

const InputPassword = React.forwardRef<HTMLInputElement, InputPasswordProps>(
  ({ className, iconEyeOffProps, iconEyeProps, ...props }, ref) => {
    const [showPassword, setShowPassword] = React.useState(false);
    return (
      <div className="relative rounded-md">
        <Input
          type={showPassword ? "text" : "password"}
          className={className}
          ref={ref}
          {...props}
        />
        <Button
          type="button"
          size="icon"
          variant="ghost"
          className="absolute right-1 top-1/2 size-6 -translate-y-1/2 rounded-md text-muted-foreground"
          onClick={() => {
            setShowPassword((prev) => !prev);
          }}
        >
          {showPassword ? (
            <Icons.eye {...iconEyeProps} />
          ) : (
            <Icons.eyeOff {...iconEyeOffProps} />
          )}
        </Button>
      </div>
    );
  },
);

InputPassword.displayName = "InputPassword";

export default InputPassword;

// apps/website-sveltekit/src/lib/components/ui/input-password/input-password.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";
  import { Icons } from "$lib/components/icon/index.js";
  import { Button } from "$lib/components/ui/button";
  import { cn } from "$lib/utils.js";
  import { EyeOff } from "lucide-svelte";

  import type { InputEvents } from "./index.js";

  type $$Props = Omit<HTMLInputAttributes, "type">;
  type $$Events = InputEvents;

  let className: $$Props["class"] = undefined;
  let showPassword = false;
  export let value: $$Props["value"] = undefined;
  export { className as class };

  // Workaround for https://github.com/sveltejs/svelte/issues/9305
  // Fixed in Svelte 5, but not backported to 4.x.
  export let readonly: $$Props["readonly"] = undefined;

  const onClickInputType = () => {
    showPassword = !showPassword;
  };
</script>

<div class="relative rounded-md">
  {#if showPassword}
    <input
      type="text"
      class={cn(
        "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
        className,
      )}
      bind:value
      {readonly}
      on:blur
      on:change
      on:click
      on:focus
      on:focusin
      on:focusout
      on:keydown
      on:keypress
      on:keyup
      on:mouseover
      on:mouseenter
      on:mouseleave
      on:mousemove
      on:paste
      on:input
      on:wheel|passive
      {...$$restProps}
    />
  {:else}
    <input
      type="password"
      class={cn(
        "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
        className,
      )}
      bind:value
      {readonly}
      on:blur
      on:change
      on:click
      on:focus
      on:focusin
      on:focusout
      on:keydown
      on:keypress
      on:keyup
      on:mouseover
      on:mouseenter
      on:mouseleave
      on:mousemove
      on:paste
      on:input
      on:wheel|passive
      {...$$restProps}
    />
  {/if}

  <Button
    type="button"
    variant="ghost"
    size="icon"
    class="absolute right-1 top-1/2 size-6 -translate-y-1/2 rounded-md text-muted-foreground"
    on:click={onClickInputType}
  >
    {#if showPassword}
      <Icons.eye />
    {:else}
      <Icons.eyeOff />
    {/if}
  </Button>
</div>
